/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author LEGION 5
 */
public class Data_Mahasiswa extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    
    public Data_Mahasiswa() {
        initComponents();
        setTitle("FORM MAHASISWA");
        koneksi ();
        kosongkan (); 
    }
    
    private void koneksi (){
     try {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/aplikasi_mahasiswa", "root", "1234");
         stat=con.createStatement();
         } 
     catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}   
    }

    private void kosongkan(){
     NIM_mahasiswa.setText("");
     Nama_mahasiswa.setText("");
     JK_mahasiswa.setSelectedIndex(-1);
     email_mahasiswa.setText("");
     alamat_mahasiswa.setText("");
     NIM_mahasiswa.requestFocus();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NIM_mahasiswa = new javax.swing.JTextField();
        Nama_mahasiswa = new javax.swing.JTextField();
        JK_mahasiswa = new javax.swing.JComboBox<>();
        email_mahasiswa = new javax.swing.JTextField();
        alamat_mahasiswa = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        search = new javax.swing.JButton();
        lihat = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        NIM_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIM_mahasiswaActionPerformed(evt);
            }
        });
        NIM_mahasiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NIM_mahasiswaKeyTyped(evt);
            }
        });
        jPanel1.add(NIM_mahasiswa);
        NIM_mahasiswa.setBounds(230, 90, 280, 30);
        jPanel1.add(Nama_mahasiswa);
        Nama_mahasiswa.setBounds(230, 140, 280, 30);

        JK_mahasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan", " " }));
        JK_mahasiswa.setSelectedIndex(-1);
        JK_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JK_mahasiswaActionPerformed(evt);
            }
        });
        jPanel1.add(JK_mahasiswa);
        JK_mahasiswa.setBounds(230, 200, 100, 22);
        jPanel1.add(email_mahasiswa);
        email_mahasiswa.setBounds(230, 250, 280, 30);
        jPanel1.add(alamat_mahasiswa);
        alamat_mahasiswa.setBounds(230, 300, 280, 30);

        edit.setText("Edit");
        jPanel1.add(edit);
        edit.setBounds(120, 360, 72, 23);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus);
        hapus.setBounds(220, 360, 72, 23);

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan);
        simpan.setBounds(320, 360, 72, 23);

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(410, 360, 72, 23);

        lihat.setText("Lihat");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });
        jPanel1.add(lihat);
        lihat.setBounds(500, 360, 72, 23);

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel1.add(Menu);
        Menu.setBounds(630, 10, 72, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA MAHASISWA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 30, 360, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 100, 60, 17);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JENIS KELAMIN");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 200, 150, 26);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 150, 61, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMAIL");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(140, 250, 60, 26);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ALAMAT");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 300, 90, 26);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/universitas-pembangunan-nasional-veteran-jakarta-upnvj-di-pondok-labu_210729153949-397_1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-3, 0, 720, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NIM_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIM_mahasiswaActionPerformed
        // TODO add your handling code here:
        try{
            res=stat.executeQuery("select * from mahasiswa where "+ "Nim='" + NIM_mahasiswa.getText()
                +"'" ); while (res.next())
                { 
                    Nama_mahasiswa.setText(res.getString("Nama"));
                    JK_mahasiswa.setSelectedItem(res.getString("Jenis_Kelamin"));
                    email_mahasiswa.setText(res.getString("Email"));
                    alamat_mahasiswa.setText(res.getString("Alamat"));
                }    
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_NIM_mahasiswaActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try {
         stat.executeUpdate("insert into mahasiswa values ("
             + "'" + NIM_mahasiswa.getText()+"',"
             + "'" + Nama_mahasiswa.getText()+"',"
             + "'" + JK_mahasiswa.getSelectedItem()+ "',"
             + "'" + email_mahasiswa.getText()+"',"
             + "'" + alamat_mahasiswa.getText()+"')");
         kosongkan();
         JOptionPane.showMessageDialog(null, "Data anda berhasil dimasukkan");
         new Data_Mahasiswa().setVisible(true);
         dispose();
         } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "terjadi kesalahan : "+e);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
         int ok=JOptionPane.showConfirmDialog(null, "Apakah yakin ingin menghapus?", "Confirmation", 
                JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0) {
         try {
             String sql="delete from mahasiswa where Nim='"+NIM_mahasiswa.getText()+"'";
             PreparedStatement st=con.prepareStatement (sql);
             st.executeUpdate();
             kosongkan();
             JOptionPane.showMessageDialog(null, "Delete Data Sukses");
             new Data_Mahasiswa().setVisible(true);
             dispose();
         } 
         catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Delete Data Gagal");
         }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try {
            res=stat.executeQuery("select * from mahasiswa where "+ "Nim='" +NIM_mahasiswa.getText()
            +"'" ); while (res.next()) { 
                    Nama_mahasiswa.setText(res.getString("Nama"));
                    JK_mahasiswa.setSelectedItem(res.getString("Jenis_Kelamin"));
                    email_mahasiswa.setText(res.getString("Email"));
                    alamat_mahasiswa.setText(res.getString("Alamat"));
    }
                }
        catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                    }
    }//GEN-LAST:event_searchActionPerformed

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        // TODO add your handling code here:
        new Tabel_Mahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_lihatActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        new Menu_Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void NIM_mahasiswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NIM_mahasiswaKeyTyped
        // TODO add your handling code here:
         char NIM=evt.getKeyChar();
        if(!(Character.isDigit(NIM))) {
            evt.consume();
        }
    }//GEN-LAST:event_NIM_mahasiswaKeyTyped

    private void JK_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JK_mahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JK_mahasiswaActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> JK_mahasiswa;
    private javax.swing.JButton Menu;
    public javax.swing.JTextField NIM_mahasiswa;
    public javax.swing.JTextField Nama_mahasiswa;
    public javax.swing.JTextField alamat_mahasiswa;
    private javax.swing.JButton edit;
    public javax.swing.JTextField email_mahasiswa;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lihat;
    private javax.swing.JButton search;
    private javax.swing.JButton simpan;
    // End of variables declaration//GEN-END:variables
}
