/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS;

import javax.swing.JOptionPane;

/**
 *
 * @author Rama
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        app_username = new javax.swing.JTextField();
        app_password = new javax.swing.JPasswordField();
        app_login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APLIKASI UANG KAS MAHASISWA");
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 120, 680, 50);

        app_username.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        app_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        app_username.setText("username");
        app_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app_usernameMouseClicked(evt);
            }
        });
        app_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                app_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(app_username);
        app_username.setBounds(260, 210, 250, 50);
        jPanel1.add(app_password);
        app_password.setBounds(260, 300, 250, 60);

        app_login.setForeground(new java.awt.Color(0, 0, 5));
        app_login.setText("LOGIN");
        app_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        app_login.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        app_login.setName(""); // NOI18N
        app_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                app_loginActionPerformed(evt);
            }
        });
        jPanel1.add(app_login);
        app_login.setBounds(350, 400, 72, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmad\\Desktop\\UAS\\Prak PBO\\universitas-pembangunan-nasional-veteran-jakarta-upnvj-di-pondok-labu_.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 761, 503);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void app_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_app_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_app_usernameActionPerformed

    private void app_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_app_loginActionPerformed
        String username = "1";
        String password = "1";
        if (username.equalsIgnoreCase(app_username.getText ()) && 
                password.equalsIgnoreCase(app_password. getText())){
            this.setVisible(false);
            new Menu_Utama(). setVisible(true);
            javax.swing.JOptionPane.showMessageDialog(null, "ANDA BERHASIL LOGIN");
            dispose();
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "MAAF USER DAN PASSWORD ANDA SALAH", "Error",
                        JOptionPane.ERROR_MESSAGE);
            app_username.setText("UserName");
            app_password.setText("password");
            app_username.requestFocus();
        }
        
    }//GEN-LAST:event_app_loginActionPerformed

    private void app_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app_usernameMouseClicked
        // TODO add your handling code here:
        app_username.setText("");
    }//GEN-LAST:event_app_usernameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton app_login;
    private javax.swing.JPasswordField app_password;
    private javax.swing.JTextField app_username;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
