/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LEGION 5 PRO
 */
public class Tabel_Mahasiswa extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;

    public Tabel_Mahasiswa() {
        initComponents();
        setTitle("TABLE DATA MAHASISWA");
        koneksi();
        tabel ();
        Tabel_mahasiswa.setAutoCreateRowSorter(true);
    }
    
    private void koneksi (){
        try {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/aplikasi_mahasiswa", "root", "1234");
         stat=con.createStatement();
         } 
        catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}
        }
    
    private void tabel (){
        DefaultTableModel x= new DefaultTableModel();
        x.addColumn("NIM");
        x.addColumn("Nama");
        x.addColumn("Jenis_Kelamin");
        x.addColumn("Email");
        x.addColumn("Alamat");
        Tabel_mahasiswa.setModel(x); 
        try{ 
            res= stat.executeQuery("select * from mahasiswa");
            while (res.next()) {
            x.addRow(new Object[]{ res.getString("NIM"),
            res.getString("Nama"),
            res.getString("Jenis_Kelamin"),
            res.getString("Email"),
            res.getString("Alamat")
                    });
                }
            }       
        catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
        }    
        }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel_mahasiswa = new javax.swing.JTable();
        pilih_mahasiswa = new javax.swing.JButton();
        pilih_uang_kas = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Tabel_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jenis Kelamin", "Email", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(Tabel_mahasiswa);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(130, 70, 470, 260);

        pilih_mahasiswa.setText("Pilih Mahaisswa");
        pilih_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih_mahasiswaActionPerformed(evt);
            }
        });
        jPanel1.add(pilih_mahasiswa);
        pilih_mahasiswa.setBounds(230, 350, 120, 23);

        pilih_uang_kas.setText("Pilih Uang Kas");
        pilih_uang_kas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih_uang_kasActionPerformed(evt);
            }
        });
        jPanel1.add(pilih_uang_kas);
        pilih_uang_kas.setBounds(370, 350, 120, 23);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(630, 10, 72, 23);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TABEL MAHASISWA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 0, 370, 70);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/universitas-pembangunan-nasional-veteran-jakarta-upnvj-di-pondok-labu_210729153949-397_1.jpg"))); // NOI18N
        bg.setText("jLabel1");
        jPanel1.add(bg);
        bg.setBounds(0, 0, 720, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Data_Mahasiswa data = new  Data_Mahasiswa();
    private void pilih_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih_mahasiswaActionPerformed
        // TODO add your handling code here:
        int index = Tabel_mahasiswa.getSelectedRow();
        
        TableModel model = Tabel_mahasiswa.getModel();
        
        String nim = model.getValueAt(index, 0).toString();
        String nama = model.getValueAt(index, 1).toString();
        String jk = model.getValueAt(index, 2).toString();
        String Email = model.getValueAt(index, 3).toString();
        String alamat = model.getValueAt(index, 4).toString();
      
       
        data.setVisible(true);
        data.pack();
        data.setLocationRelativeTo(null);
        data.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        data.NIM_mahasiswa.setText(nim);
        data.Nama_mahasiswa.setText(nama);
        data.JK_mahasiswa.setSelectedItem(jk);
        data.email_mahasiswa.setText(Email);
        data.alamat_mahasiswa.setText(alamat);
        dispose();
    }//GEN-LAST:event_pilih_mahasiswaActionPerformed

    UangKas JFrame = new  UangKas();
    private void pilih_uang_kasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih_uang_kasActionPerformed
        // TODO add your handling code here:
        int index = Tabel_mahasiswa.getSelectedRow();
        
        TableModel model = Tabel_mahasiswa.getModel();
        
        String nama = model.getValueAt(index, 1).toString();
      
       
        JFrame.setVisible(true);
        JFrame.pack();
        JFrame.setLocationRelativeTo(null);
        JFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        JFrame.Uangkas_Nama1.setText(nama);
        dispose();
    }//GEN-LAST:event_pilih_uang_kasActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new JFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabel_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabel_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabel_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabel_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabel_Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel_mahasiswa;
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pilih_mahasiswa;
    private javax.swing.JButton pilih_uang_kas;
    // End of variables declaration//GEN-END:variables
}
