/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS;


import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Driver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.awt.event.KeyEvent;
import java.sql.Date;

/**
 *
 * @author Rama
 */
public class UangKas extends javax.swing.JFrame {

    /**
     * Creates new form UangKas
     */
    
     private Connection con;
    private Statement stat;
    private ResultSet res;
    private String t, keterangan;
    private DefaultTableModel dtm;
    /**
     * Creates new form UangKas
     */
    public UangKas() {
        initComponents();
        setTitle("LAPORAN UANGKAS");
        koneksi ();
        kosongkan ();
        tabel ();
        //rata kiri dan kanan
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
           (screenSize.width - frameSize.width) / 3,
           (screenSize.height - frameSize.height) /4);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Uangkas_No = new javax.swing.JLabel();
        Uangkas_Tanggal = new javax.swing.JLabel();
        Uangkas_nama = new javax.swing.JLabel();
        Uangkas_Keterangan = new javax.swing.JLabel();
        Rp1 = new javax.swing.JLabel();
        Rp2 = new javax.swing.JLabel();
        Uangkas_No1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Uangkas_Table = new javax.swing.JTable();
        Uangkas_Edit = new javax.swing.JButton();
        Uangkas_Simpan = new javax.swing.JButton();
        Uangkas_Clear = new javax.swing.JButton();
        Uangkas_Hapus = new javax.swing.JButton();
        Uangkas_Search = new javax.swing.JButton();
        Pembayaran = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pengeluaran = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Uangkas_Nama1 = new javax.swing.JTextField();
        Uangkas_Lihat = new javax.swing.JButton();
        Uangkas_Pembayaran = new javax.swing.JTextField();
        Uangkas_Pengeluaran = new javax.swing.JTextField();
        Uangkas_SaldoAkhir1 = new javax.swing.JTextField();
        Uangkas_Keterangan1 = new javax.swing.JTextField();
        Uangkas_2minggu1 = new javax.swing.JTextField();
        Uangkas_Menu = new javax.swing.JButton();
        Uangkas_Tanggal1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(810, 520));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Laporan Keuangan Mahasiswa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(123, 12, 508, 48);

        Uangkas_No.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Uangkas_No.setForeground(new java.awt.Color(255, 255, 255));
        Uangkas_No.setText("No.");
        jPanel1.add(Uangkas_No);
        Uangkas_No.setBounds(117, 75, 19, 16);

        Uangkas_Tanggal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Uangkas_Tanggal.setForeground(new java.awt.Color(255, 255, 255));
        Uangkas_Tanggal.setText("Tanggal");
        jPanel1.add(Uangkas_Tanggal);
        Uangkas_Tanggal.setBounds(86, 115, 50, 16);

        Uangkas_nama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Uangkas_nama.setForeground(new java.awt.Color(255, 255, 255));
        Uangkas_nama.setText("Nama");
        jPanel1.add(Uangkas_nama);
        Uangkas_nama.setBounds(104, 153, 32, 16);

        Uangkas_Keterangan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Uangkas_Keterangan.setForeground(new java.awt.Color(255, 255, 255));
        Uangkas_Keterangan.setText("Keterangan");
        jPanel1.add(Uangkas_Keterangan);
        Uangkas_Keterangan.setBounds(66, 197, 70, 16);

        Rp1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Rp1.setForeground(new java.awt.Color(255, 255, 255));
        Rp1.setText("Rp.");
        jPanel1.add(Rp1);
        Rp1.setBounds(505, 75, 20, 16);

        Rp2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Rp2.setForeground(new java.awt.Color(255, 255, 255));
        Rp2.setText("Rp.");
        jPanel1.add(Rp2);
        Rp2.setBounds(505, 115, 20, 16);

        Uangkas_No1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_No1ActionPerformed(evt);
            }
        });
        Uangkas_No1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Uangkas_No1KeyTyped(evt);
            }
        });
        jPanel1.add(Uangkas_No1);
        Uangkas_No1.setBounds(154, 72, 120, 22);

        Uangkas_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Uangkas_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Uangkas_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Uangkas_Table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(31, 286, 733, 223);

        Uangkas_Edit.setText("Edit");
        Uangkas_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_EditActionPerformed(evt);
            }
        });
        jPanel1.add(Uangkas_Edit);
        Uangkas_Edit.setBounds(88, 245, 72, 23);

        Uangkas_Simpan.setText("Simpan");
        Uangkas_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_SimpanActionPerformed(evt);
            }
        });
        jPanel1.add(Uangkas_Simpan);
        Uangkas_Simpan.setBounds(201, 245, 72, 23);

        Uangkas_Clear.setText("Clear");
        Uangkas_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Uangkas_Clear);
        Uangkas_Clear.setBounds(322, 245, 72, 23);

        Uangkas_Hapus.setText("Hapus");
        Uangkas_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Uangkas_Hapus);
        Uangkas_Hapus.setBounds(439, 245, 72, 23);

        Uangkas_Search.setText("Search");
        Uangkas_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Uangkas_Search);
        Uangkas_Search.setBounds(556, 245, 72, 23);

        Pembayaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Pembayaran.setForeground(new java.awt.Color(255, 255, 255));
        Pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembayaranActionPerformed(evt);
            }
        });
        jPanel1.add(Pembayaran);
        Pembayaran.setBounds(320, 70, 30, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pembayaran");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 80, 90, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pengeluaran");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 120, 90, 20);

        Pengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Pengeluaran.setForeground(new java.awt.Color(255, 255, 255));
        Pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PengeluaranActionPerformed(evt);
            }
        });
        jPanel1.add(Pengeluaran);
        Pengeluaran.setBounds(323, 113, 130, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Saldo Akhir");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(455, 156, 70, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Uang Kas / 2 minggu");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(405, 194, 120, 16);

        Uangkas_Nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_Nama1ActionPerformed(evt);
            }
        });
        jPanel1.add(Uangkas_Nama1);
        Uangkas_Nama1.setBounds(154, 153, 120, 22);

        Uangkas_Lihat.setText("Lihat");
        Uangkas_Lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_LihatActionPerformed(evt);
            }
        });
        jPanel1.add(Uangkas_Lihat);
        Uangkas_Lihat.setBounds(319, 153, 72, 23);

        Uangkas_Pembayaran.setText("0");
        Uangkas_Pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_PembayaranActionPerformed(evt);
            }
        });
        Uangkas_Pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Uangkas_PembayaranKeyTyped(evt);
            }
        });
        jPanel1.add(Uangkas_Pembayaran);
        Uangkas_Pembayaran.setBounds(572, 72, 112, 22);

        Uangkas_Pengeluaran.setText("0");
        Uangkas_Pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_PengeluaranActionPerformed(evt);
            }
        });
        Uangkas_Pengeluaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Uangkas_PengeluaranKeyTyped(evt);
            }
        });
        jPanel1.add(Uangkas_Pengeluaran);
        Uangkas_Pengeluaran.setBounds(572, 112, 112, 22);

        Uangkas_SaldoAkhir1.setText("0");
        Uangkas_SaldoAkhir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_SaldoAkhir1ActionPerformed(evt);
            }
        });
        Uangkas_SaldoAkhir1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Uangkas_SaldoAkhir1KeyTyped(evt);
            }
        });
        jPanel1.add(Uangkas_SaldoAkhir1);
        Uangkas_SaldoAkhir1.setBounds(572, 153, 112, 22);
        jPanel1.add(Uangkas_Keterangan1);
        Uangkas_Keterangan1.setBounds(154, 194, 120, 22);

        Uangkas_2minggu1.setText("10.000");
        jPanel1.add(Uangkas_2minggu1);
        Uangkas_2minggu1.setBounds(570, 190, 100, 22);

        Uangkas_Menu.setText("Menu");
        Uangkas_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uangkas_MenuActionPerformed(evt);
            }
        });
        jPanel1.add(Uangkas_Menu);
        Uangkas_Menu.setBounds(720, 20, 72, 23);
        jPanel1.add(Uangkas_Tanggal1);
        Uangkas_Tanggal1.setBounds(150, 110, 120, 22);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/universitas-pembangunan-nasional-veteran-jakarta-upnvj-di-pondok-labu_210729153949-397.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jLabel10.setMaximumSize(new java.awt.Dimension(810, 520));
        jLabel10.setPreferredSize(new java.awt.Dimension(810, 520));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 810, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void koneksi(){
     try {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/aplikasi_mahasiswa", "root", "1234");
         stat=con.createStatement();
         } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}   
    }
    
    private void kosongkan(){
     Uangkas_No1.setText("");
     Uangkas_Tanggal1.setDate(null);
     Uangkas_Nama1.setText("");
     Uangkas_Keterangan1.setText("");
     Pembayaran.setText("");
     Pengeluaran.setText("");
     Uangkas_SaldoAkhir1.setText("");
     Pembayaran.setSelected(false);
     Pengeluaran.setSelected(false);
     Uangkas_No1.requestFocus();
    }
    
    private void tabel (){
        DefaultTableModel t= new DefaultTableModel();
        t.addColumn("No");
        t.addColumn("Tanggal");
        t.addColumn("Nama");
        t.addColumn("Pemasukan");
        t.addColumn("Pengeluaran");
        t.addColumn("Saldo_Akhir");
        t.addColumn("Keterangan");
        Uangkas_Table.setModel(t); try{ res= stat.executeQuery("select * from uangkas");
    while (res.next()) {
    t.addRow(new Object[]{ 
      res.getString("No"),
      res.getString("Tanggal"),
      res.getString("Nama"),
      res.getString("Pemasukan"),
      res.getString("Pengeluaran"),
      res.getString("Saldo_Akhir"),
      res.getString("Keterangan")
        });}
}catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);}    
    }
    private void Uangkas_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_EditActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin mengedit data?","Confirmation",
                JOptionPane.YES_NO_OPTION);
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(tampilan);
        String Tanggal=String.valueOf(fm.format(Uangkas_Tanggal1.getDate()));
    try{
    String sql = "update uangkas set No=?,Tanggal=?,Nama=?,Pemasukan=?,Pengeluaran=?,"
            + "SaldoAkhir=?,Keterangan=? where No='"
                    + Uangkas_No1.getText()+"'";
    PreparedStatement st=con.prepareStatement(sql);
    if(ok==0){
    try{
    st.setString(1,Uangkas_No1.getText());
    st.setString(2,Tanggal);
    st.setString(3,Uangkas_Nama1.getText());
    st.setString(4,Uangkas_Pembayaran.getText());
    st.setString(5,Uangkas_Pengeluaran.getText());
    st.setString(6,Uangkas_SaldoAkhir1.getText());
    st.setString(7,Uangkas_Keterangan.getText());
    st.executeUpdate();
    kosongkan();
    JOptionPane.showMessageDialog(null,"Edit Data Sukses");
    new UangKas().setVisible(true);
    dispose();
    }catch (Exception e){
    JOptionPane.showMessageDialog(null, "Edit Data Gagal");}}
    }catch (Exception e){}
    }//GEN-LAST:event_Uangkas_EditActionPerformed

    private void Uangkas_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_SimpanActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(tampilan);
        String Tanggal=String.valueOf(fm.format(Uangkas_Tanggal1.getDate()));
        
        try {
         stat.executeUpdate("insert into uangkas values ("
             + "'" + Uangkas_No1.getText()+"',"
             + "'" + Tanggal+"',"
             + "'" + Uangkas_Nama1.getText()+"',"
             + "'" + Uangkas_Keterangan1.getText()+"',"
             + "'" + Uangkas_Pembayaran.getText()+"',"
             + "'" + Uangkas_Pengeluaran.getText()+"',"
             + "'" + Uangkas_SaldoAkhir1.getText()+"')");
         kosongkan();
         JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
         new UangKas().setVisible(true);
         dispose();
         } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data! : "+e);
        }
    }//GEN-LAST:event_Uangkas_SimpanActionPerformed

    private void Uangkas_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_ClearActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_Uangkas_ClearActionPerformed

    private void Uangkas_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_HapusActionPerformed

        int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin menghapus data?","Confirmation",
                JOptionPane.YES_NO_OPTION);
         try{
             String sql="delete from uangkas where No='"+Uangkas_No1.getText()+"'";
             PreparedStatement st=con.prepareStatement (sql);
             st.executeUpdate();
             kosongkan();
             JOptionPane.showMessageDialog(null, "Delete Data Sukses");
             new UangKas().setVisible(true);
             dispose();
         } catch (Exception e)
         {
             JOptionPane.showMessageDialog(null, "Delete Data Gagal");
         }
    }//GEN-LAST:event_Uangkas_HapusActionPerformed

    private void Uangkas_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_SearchActionPerformed

         try {
            res=stat.executeQuery("select * from uangkas where "+ "No='" +Uangkas_No1.getText()
            +"'" ); while (res.next())
            { Uangkas_Tanggal1.setDate(res.getDate("Tanggal"));
              Uangkas_Nama1.setText(res.getString("Nama"));
              Uangkas_Pembayaran.setText(res.getString("Pemasukan"));
              Uangkas_Pengeluaran.setText(res.getString("Pengeluaran"));
              Uangkas_SaldoAkhir1.setText(res.getString("Saldo_Akhir"));
              Uangkas_Keterangan.setText(res.getString("Keterangan"));
            }
        }catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_Uangkas_SearchActionPerformed

    private void Uangkas_PembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_PembayaranActionPerformed

    }//GEN-LAST:event_Uangkas_PembayaranActionPerformed

    private void Uangkas_PengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_PengeluaranActionPerformed

    }//GEN-LAST:event_Uangkas_PengeluaranActionPerformed

    private void Uangkas_SaldoAkhir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_SaldoAkhir1ActionPerformed

    }//GEN-LAST:event_Uangkas_SaldoAkhir1ActionPerformed

    private void Uangkas_Nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_Nama1ActionPerformed

    }//GEN-LAST:event_Uangkas_Nama1ActionPerformed

    private void PembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembayaranActionPerformed

                keterangan = "Uang Masuk";
        Pengeluaran.setSelected(false);
        Uangkas_Keterangan1.setText(""+keterangan);
    }//GEN-LAST:event_PembayaranActionPerformed

    private void PengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengeluaranActionPerformed

        keterangan = "Uang Keluar";
        Pembayaran.setSelected(false);
        Uangkas_Keterangan1.setText(""+keterangan);
    }//GEN-LAST:event_PengeluaranActionPerformed

    private void Uangkas_No1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_No1ActionPerformed

        try{
            res=stat.executeQuery("select * from uangkas where "+ "No='" + Uangkas_No1.getText()
                +"'" ); while (res.next())
                { Uangkas_Tanggal1.setDate (res.getDate("Tanggal"));
                Uangkas_Nama1.setText(res.getString("Nama"));
                Uangkas_Pembayaran.setText(res.getString("Pemasukan"));
                Uangkas_Pengeluaran.setText(res.getString("Pengeluaran"));
                Uangkas_SaldoAkhir1.setText(res.getString("Saldo_Akhir"));
                Uangkas_Keterangan1.setText(res.getString("Keterangan"));
                }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_Uangkas_No1ActionPerformed

    private void Uangkas_LihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_LihatActionPerformed

        new Tabel_Mahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_Uangkas_LihatActionPerformed

    private void Uangkas_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uangkas_MenuActionPerformed

        new Menu_Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_Uangkas_MenuActionPerformed

    private void Uangkas_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Uangkas_TableMouseClicked

        int i = Uangkas_Table.getSelectedRow();
        if(i==-1){
        return;
        }
        String code = (String)Uangkas_Table.getValueAt(i,0);
        String code1 = (String)Uangkas_Table.getValueAt(i,1);
        String code2 = (String)Uangkas_Table.getValueAt(i,2);
        String code3 = (String)Uangkas_Table.getValueAt(i,3);
        String code4 = (String)Uangkas_Table.getValueAt(i,4);
        String code5 = (String)Uangkas_Table.getValueAt(i,5);
        String code6 = (String)Uangkas_Table.getValueAt(i,6);
//        String code7 = (String)Uangkas_Table.getValueAt(i,7);

        
        Uangkas_No1.setText(code);
        Uangkas_Tanggal1.setDateFormatString(code1);
        Uangkas_Nama1.setText(code2);
        Uangkas_Pembayaran.setText(code3);
        Uangkas_Pengeluaran.setText(code4);
        Uangkas_SaldoAkhir1.setText(code5);
        Uangkas_Keterangan.setText(code6);
    }//GEN-LAST:event_Uangkas_TableMouseClicked

    private void Uangkas_No1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Uangkas_No1KeyTyped
        // TODO add your handling code here:
        char uas=evt.getKeyChar();
        if(!(Character.isDigit(uas)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Uangkas_No1KeyTyped

    private void Uangkas_PembayaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Uangkas_PembayaranKeyTyped
        // TODO add your handling code here:
        char uas=evt.getKeyChar();
        if(!(Character.isDigit(uas)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Uangkas_PembayaranKeyTyped

    private void Uangkas_PengeluaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Uangkas_PengeluaranKeyTyped
        // TODO add your handling code here:
        char uas=evt.getKeyChar();
        if(!(Character.isDigit(uas)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Uangkas_PengeluaranKeyTyped

    private void Uangkas_SaldoAkhir1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Uangkas_SaldoAkhir1KeyTyped
        // TODO add your handling code here:
        char uas=evt.getKeyChar();
        if(!(Character.isDigit(uas)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Uangkas_SaldoAkhir1KeyTyped

    private void Uangkas_Tanggal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Uangkas_Tanggal1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Uangkas_Tanggal1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UangKas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Pembayaran;
    private javax.swing.JCheckBox Pengeluaran;
    private javax.swing.JLabel Rp1;
    private javax.swing.JLabel Rp2;
    private javax.swing.JTextField Uangkas_2minggu1;
    private javax.swing.JButton Uangkas_Clear;
    private javax.swing.JButton Uangkas_Edit;
    private javax.swing.JButton Uangkas_Hapus;
    private javax.swing.JLabel Uangkas_Keterangan;
    private javax.swing.JTextField Uangkas_Keterangan1;
    private javax.swing.JButton Uangkas_Lihat;
    private javax.swing.JButton Uangkas_Menu;
    public javax.swing.JTextField Uangkas_Nama1;
    private javax.swing.JLabel Uangkas_No;
    private javax.swing.JTextField Uangkas_No1;
    private javax.swing.JTextField Uangkas_Pembayaran;
    private javax.swing.JTextField Uangkas_Pengeluaran;
    private javax.swing.JTextField Uangkas_SaldoAkhir1;
    private javax.swing.JButton Uangkas_Search;
    private javax.swing.JButton Uangkas_Simpan;
    private javax.swing.JTable Uangkas_Table;
    private javax.swing.JLabel Uangkas_Tanggal;
    private com.toedter.calendar.JDateChooser Uangkas_Tanggal1;
    private javax.swing.JLabel Uangkas_nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

//    private void initComponents() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
}
